// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1
{

    [OutputType]
    public sealed class TidbClusterSpecTidbService
    {
        public readonly bool ExposeStatus;
        public readonly string ExternalTrafficPolicy;
        public readonly int MysqlNodePort;
        public readonly int StatusNodePort;

        [OutputConstructor]
        private TidbClusterSpecTidbService(
            bool exposeStatus,

            string externalTrafficPolicy,

            int mysqlNodePort,

            int statusNodePort)
        {
            ExposeStatus = exposeStatus;
            ExternalTrafficPolicy = externalTrafficPolicy;
            MysqlNodePort = mysqlNodePort;
            StatusNodePort = statusNodePort;
        }
    }
}
