# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "admin_secret": "adminSecret",
    "api_version": "apiVersion",
    "external_host": "externalHost",
    "external_port": "externalPort",
    "last_update": "lastUpdate",
    "persistent_volume_claim": "persistentVolumeClaim",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "adminSecret": "admin_secret",
    "apiVersion": "api_version",
    "externalHost": "external_host",
    "externalPort": "external_port",
    "lastUpdate": "last_update",
    "persistentVolumeClaim": "persistent_volume_claim",
}
