// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1
{

    [OutputType]
    public sealed class SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternal
    {
        /// <summary>
        /// metricName is the name of the metric in question.
        /// </summary>
        public readonly string MetricName;
        /// <summary>
        /// metricSelector is used to identify a specific time series within a given metric.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1.SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternalMetricSelector MetricSelector;
        /// <summary>
        /// targetAverageValue is the target per-pod value of global metric (as a quantity). Mutually exclusive with TargetValue.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1.SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternalTargetAverageValue TargetAverageValue;
        /// <summary>
        /// targetValue is the target value of the metric (as a quantity). Mutually exclusive with TargetAverageValue.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1.SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternalTargetValue TargetValue;

        [OutputConstructor]
        private SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternal(
            string metricName,

            Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1.SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternalMetricSelector metricSelector,

            Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1.SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternalTargetAverageValue targetAverageValue,

            Pulumi.Kubernetes.Types.Outputs.Machinelearning.V1.SeldonDeploymentSpecPredictorsComponentSpecsHpaSpecMetricsExternalTargetValue targetValue)
        {
            MetricName = metricName;
            MetricSelector = metricSelector;
            TargetAverageValue = targetAverageValue;
            TargetValue = targetValue;
        }
    }
}
