// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Snapscheduler.V1
{

    [OutputType]
    public sealed class SnapshotScheduleStatusConditions
    {
        public readonly string LastHeartbeatTime;
        public readonly string LastTransitionTime;
        public readonly string Message;
        public readonly string Reason;
        public readonly string Status;
        /// <summary>
        /// ConditionType is the state of the operator's reconciliation functionality.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private SnapshotScheduleStatusConditions(
            string lastHeartbeatTime,

            string lastTransitionTime,

            string message,

            string reason,

            string status,

            string type)
        {
            LastHeartbeatTime = lastHeartbeatTime;
            LastTransitionTime = lastTransitionTime;
            Message = message;
            Reason = reason;
            Status = status;
            Type = type;
        }
    }
}
