// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1
{

    /// <summary>
    /// Contains configuration of Prometheus to monitor the storage cluster.
    /// </summary>
    public class StorageClusterSpecMonitoringPrometheusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Flag indicating whether Prometheus stack needs to be enabled and deployed by the Storage operator.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// If this flag is enabled it will expose the storage cluster metrics to Prometheus.
        /// </summary>
        [Input("exportMetrics")]
        public Input<bool>? ExportMetrics { get; set; }

        /// <summary>
        /// Specifies the remote write endpoint for Prometheus.
        /// </summary>
        [Input("remoteWriteEndpoint")]
        public Input<string>? RemoteWriteEndpoint { get; set; }

        public StorageClusterSpecMonitoringPrometheusArgs()
        {
        }
    }
}
