// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1
{

    /// <summary>
    /// Contains spec of autopilot component for storage driver.
    /// </summary>
    public class StorageClusterSpecAutopilotArgs : Pulumi.ResourceArgs
    {
        [Input("args")]
        private InputMap<object>? _args;

        /// <summary>
        /// It is a map of arguments provided to autopilot. Example: log-level: debug
        /// </summary>
        public InputMap<object> Args
        {
            get => _args ?? (_args = new InputMap<object>());
            set => _args = value;
        }

        /// <summary>
        /// Flag indicating whether autopilot needs to be enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("env")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.StorageClusterSpecAutopilotEnvArgs>? _env;

        /// <summary>
        /// List of environment variables used by autopilot. This is an array of Kubernetes EnvVar where the value can be given directly or from a source like field, config map or secret.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.StorageClusterSpecAutopilotEnvArgs> Env
        {
            get => _env ?? (_env = new InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.StorageClusterSpecAutopilotEnvArgs>());
            set => _env = value;
        }

        /// <summary>
        /// Docker image of the autopilot container.
        /// </summary>
        [Input("image")]
        public Input<string>? Image { get; set; }

        /// <summary>
        /// Flag indicating if the autopilot image needs to be locked to the given image. If the image is not locked, it can be updated by the storage driver during upgrades.
        /// </summary>
        [Input("lockImage")]
        public Input<bool>? LockImage { get; set; }

        [Input("providers")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.StorageClusterSpecAutopilotProvidersArgs>? _providers;

        /// <summary>
        /// List of input data providers to autopilot.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.StorageClusterSpecAutopilotProvidersArgs> Providers
        {
            get => _providers ?? (_providers = new InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.StorageClusterSpecAutopilotProvidersArgs>());
            set => _providers = value;
        }

        public StorageClusterSpecAutopilotArgs()
        {
        }
    }
}
