// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Migration.V1Alpha1
{

    public class MigPlanStatusIncompatibleNamespacesArgs : Pulumi.ResourceArgs
    {
        [Input("gvks", required: true)]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Migration.V1Alpha1.MigPlanStatusIncompatibleNamespacesGvksArgs>? _gvks;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Migration.V1Alpha1.MigPlanStatusIncompatibleNamespacesGvksArgs> Gvks
        {
            get => _gvks ?? (_gvks = new InputList<Pulumi.Kubernetes.Types.Inputs.Migration.V1Alpha1.MigPlanStatusIncompatibleNamespacesGvksArgs>());
            set => _gvks = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public MigPlanStatusIncompatibleNamespacesArgs()
        {
        }
    }
}
