// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1
{

    /// <summary>
    /// DatadogAgentStatus defines the observed state of DatadogAgent
    /// </summary>
    public class DatadogAgentStatusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The actual state of the Agent as an extended daemonset
        /// </summary>
        [Input("agent")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1.DatadogAgentStatusAgentArgs>? Agent { get; set; }

        /// <summary>
        /// The actual state of the Cluster Agent as a deployment
        /// </summary>
        [Input("clusterAgent")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1.DatadogAgentStatusClusterAgentArgs>? ClusterAgent { get; set; }

        /// <summary>
        /// The actual state of the Cluster Checks Runner as a deployment
        /// </summary>
        [Input("clusterChecksRunner")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1.DatadogAgentStatusClusterChecksRunnerArgs>? ClusterChecksRunner { get; set; }

        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1.DatadogAgentStatusConditionsArgs>? _conditions;

        /// <summary>
        /// Conditions Represents the latest available observations of a DatadogAgent's current state.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1.DatadogAgentStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Datadoghq.V1Alpha1.DatadogAgentStatusConditionsArgs>());
            set => _conditions = value;
        }

        public DatadogAgentStatusArgs()
        {
        }
    }
}
