// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Hive.V1
{

    [OutputType]
    public sealed class ClusterDeploymentSpecCertificateBundles
    {
        /// <summary>
        /// CertificateSecretRef is the reference to the secret that contains the certificate bundle. If the certificate bundle is to be generated, it will be generated with the name in this reference. Otherwise, it is expected that the secret should exist in the same namespace as the ClusterDeployment
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Hive.V1.ClusterDeploymentSpecCertificateBundlesCertificateSecretRef CertificateSecretRef;
        /// <summary>
        /// Generate indicates whether this bundle should have real certificates generated for it.
        /// </summary>
        public readonly bool Generate;
        /// <summary>
        /// Name is an identifier that must be unique within the bundle and must be referenced by an ingress or by the control plane serving certs
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ClusterDeploymentSpecCertificateBundles(
            Pulumi.Kubernetes.Types.Outputs.Hive.V1.ClusterDeploymentSpecCertificateBundlesCertificateSecretRef certificateSecretRef,

            bool generate,

            string name)
        {
            CertificateSecretRef = certificateSecretRef;
            Generate = generate;
            Name = name;
        }
    }
}
