// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Hive.V1
{

    [OutputType]
    public sealed class SelectorSyncSetSpecSecretMappings
    {
        /// <summary>
        /// SourceRef specifies the name and namespace of a secret on the management cluster
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Hive.V1.SelectorSyncSetSpecSecretMappingsSourceRef SourceRef;
        /// <summary>
        /// TargetRef specifies the target name and namespace of the secret on the target cluster
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Hive.V1.SelectorSyncSetSpecSecretMappingsTargetRef TargetRef;

        [OutputConstructor]
        private SelectorSyncSetSpecSecretMappings(
            Pulumi.Kubernetes.Types.Outputs.Hive.V1.SelectorSyncSetSpecSecretMappingsSourceRef sourceRef,

            Pulumi.Kubernetes.Types.Outputs.Hive.V1.SelectorSyncSetSpecSecretMappingsTargetRef targetRef)
        {
            SourceRef = sourceRef;
            TargetRef = targetRef;
        }
    }
}
