// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Kubernetes.Crds.Operators.3scaleCommunityOperator.Capabilities.V1Beta1
{
    /// <summary>
    /// Backend is the Schema for the backends API
    /// </summary>
    public partial class Backend : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// BackendSpec defines the desired state of Backend
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Capabilities.V1Beta1.BackendSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// BackendStatus defines the observed state of Backend
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Capabilities.V1Beta1.BackendStatus> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Backend resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Backend(string name, Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1.BackendArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:capabilities.3scale.net/v1beta1:Backend", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal Backend(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:capabilities.3scale.net/v1beta1:Backend", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private Backend(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:capabilities.3scale.net/v1beta1:Backend", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1.BackendArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1.BackendArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1.BackendArgs();
            args.ApiVersion = "capabilities.3scale.net/v1beta1";
            args.Kind = "Backend";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Backend resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Backend Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Backend(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1
{

    public class BackendArgs : Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// BackendSpec defines the desired state of Backend
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1.BackendSpecArgs>? Spec { get; set; }

        /// <summary>
        /// BackendStatus defines the observed state of Backend
        /// </summary>
        [Input("status")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Capabilities.V1Beta1.BackendStatusArgs>? Status { get; set; }

        public BackendArgs()
        {
        }
    }
}
