// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Camel.V1
{

    /// <summary>
    /// BuildStatus defines the observed state of Build
    /// </summary>
    public class BuildStatusArgs : Pulumi.ResourceArgs
    {
        [Input("artifacts")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusArtifactsArgs>? _artifacts;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusArtifactsArgs> Artifacts
        {
            get => _artifacts ?? (_artifacts = new InputList<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusArtifactsArgs>());
            set => _artifacts = value;
        }

        [Input("baseImage")]
        public Input<string>? BaseImage { get; set; }

        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusConditionsArgs>? _conditions;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusConditionsArgs>());
            set => _conditions = value;
        }

        [Input("digest")]
        public Input<string>? Digest { get; set; }

        /// <summary>
        /// Change to Duration / ISO 8601 when CRD uses OpenAPI spec v3 https://github.com/OAI/OpenAPI-Specification/issues/845
        /// </summary>
        [Input("duration")]
        public Input<string>? Duration { get; set; }

        [Input("error")]
        public Input<string>? Error { get; set; }

        /// <summary>
        /// Failure --
        /// </summary>
        [Input("failure")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Camel.V1.BuildStatusFailureArgs>? Failure { get; set; }

        [Input("image")]
        public Input<string>? Image { get; set; }

        /// <summary>
        /// BuildPhase --
        /// </summary>
        [Input("phase")]
        public Input<string>? Phase { get; set; }

        [Input("platform")]
        public Input<string>? Platform { get; set; }

        [Input("startedAt")]
        public Input<string>? StartedAt { get; set; }

        public BuildStatusArgs()
        {
        }
    }
}
