// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Camel.V1
{

    /// <summary>
    /// A TraitSpec contains the configuration of a trait
    /// </summary>
    public class IntegrationPlatformSpecTraitsArgs : Pulumi.ResourceArgs
    {
        [Input("configuration", required: true)]
        private InputMap<object>? _configuration;
        public InputMap<object> Configuration
        {
            get => _configuration ?? (_configuration = new InputMap<object>());
            set => _configuration = value;
        }

        public IntegrationPlatformSpecTraitsArgs()
        {
        }
    }
}
