// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// SpecialResource is the Schema for the specialresources API
type SpecialResourceType struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// SpecialResourceSpec defines the desired state of SpecialResource
	Spec map[string]interface{} `pulumi:"spec"`
	// SpecialResourceStatus defines the observed state of SpecialResource
	Status *SpecialResourceStatus `pulumi:"status"`
}

// SpecialResourceTypeInput is an input type that accepts SpecialResourceTypeArgs and SpecialResourceTypeOutput values.
// You can construct a concrete instance of `SpecialResourceTypeInput` via:
//
//          SpecialResourceTypeArgs{...}
type SpecialResourceTypeInput interface {
	pulumi.Input

	ToSpecialResourceTypeOutput() SpecialResourceTypeOutput
	ToSpecialResourceTypeOutputWithContext(context.Context) SpecialResourceTypeOutput
}

// SpecialResource is the Schema for the specialresources API
type SpecialResourceTypeArgs struct {
	ApiVersion pulumi.StringPtrInput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrInput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrInput `pulumi:"metadata"`
	// SpecialResourceSpec defines the desired state of SpecialResource
	Spec pulumi.MapInput `pulumi:"spec"`
	// SpecialResourceStatus defines the observed state of SpecialResource
	Status SpecialResourceStatusPtrInput `pulumi:"status"`
}

func (SpecialResourceTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceType)(nil)).Elem()
}

func (i SpecialResourceTypeArgs) ToSpecialResourceTypeOutput() SpecialResourceTypeOutput {
	return i.ToSpecialResourceTypeOutputWithContext(context.Background())
}

func (i SpecialResourceTypeArgs) ToSpecialResourceTypeOutputWithContext(ctx context.Context) SpecialResourceTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SpecialResourceTypeOutput)
}

// SpecialResource is the Schema for the specialresources API
type SpecialResourceTypeOutput struct{ *pulumi.OutputState }

func (SpecialResourceTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceType)(nil)).Elem()
}

func (o SpecialResourceTypeOutput) ToSpecialResourceTypeOutput() SpecialResourceTypeOutput {
	return o
}

func (o SpecialResourceTypeOutput) ToSpecialResourceTypeOutputWithContext(ctx context.Context) SpecialResourceTypeOutput {
	return o
}

func (o SpecialResourceTypeOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SpecialResourceType) *string { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

func (o SpecialResourceTypeOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SpecialResourceType) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o SpecialResourceTypeOutput) Metadata() metav1.ObjectMetaPtrOutput {
	return o.ApplyT(func(v SpecialResourceType) *metav1.ObjectMeta { return v.Metadata }).(metav1.ObjectMetaPtrOutput)
}

// SpecialResourceSpec defines the desired state of SpecialResource
func (o SpecialResourceTypeOutput) Spec() pulumi.MapOutput {
	return o.ApplyT(func(v SpecialResourceType) map[string]interface{} { return v.Spec }).(pulumi.MapOutput)
}

// SpecialResourceStatus defines the observed state of SpecialResource
func (o SpecialResourceTypeOutput) Status() SpecialResourceStatusPtrOutput {
	return o.ApplyT(func(v SpecialResourceType) *SpecialResourceStatus { return v.Status }).(SpecialResourceStatusPtrOutput)
}

type SpecialResourceMetadata struct {
}

// SpecialResourceMetadataInput is an input type that accepts SpecialResourceMetadataArgs and SpecialResourceMetadataOutput values.
// You can construct a concrete instance of `SpecialResourceMetadataInput` via:
//
//          SpecialResourceMetadataArgs{...}
type SpecialResourceMetadataInput interface {
	pulumi.Input

	ToSpecialResourceMetadataOutput() SpecialResourceMetadataOutput
	ToSpecialResourceMetadataOutputWithContext(context.Context) SpecialResourceMetadataOutput
}

type SpecialResourceMetadataArgs struct {
}

func (SpecialResourceMetadataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceMetadata)(nil)).Elem()
}

func (i SpecialResourceMetadataArgs) ToSpecialResourceMetadataOutput() SpecialResourceMetadataOutput {
	return i.ToSpecialResourceMetadataOutputWithContext(context.Background())
}

func (i SpecialResourceMetadataArgs) ToSpecialResourceMetadataOutputWithContext(ctx context.Context) SpecialResourceMetadataOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SpecialResourceMetadataOutput)
}

type SpecialResourceMetadataOutput struct{ *pulumi.OutputState }

func (SpecialResourceMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceMetadata)(nil)).Elem()
}

func (o SpecialResourceMetadataOutput) ToSpecialResourceMetadataOutput() SpecialResourceMetadataOutput {
	return o
}

func (o SpecialResourceMetadataOutput) ToSpecialResourceMetadataOutputWithContext(ctx context.Context) SpecialResourceMetadataOutput {
	return o
}

// SpecialResourceSpec defines the desired state of SpecialResource
type SpecialResourceSpec struct {
}

// SpecialResourceSpecInput is an input type that accepts SpecialResourceSpecArgs and SpecialResourceSpecOutput values.
// You can construct a concrete instance of `SpecialResourceSpecInput` via:
//
//          SpecialResourceSpecArgs{...}
type SpecialResourceSpecInput interface {
	pulumi.Input

	ToSpecialResourceSpecOutput() SpecialResourceSpecOutput
	ToSpecialResourceSpecOutputWithContext(context.Context) SpecialResourceSpecOutput
}

// SpecialResourceSpec defines the desired state of SpecialResource
type SpecialResourceSpecArgs struct {
}

func (SpecialResourceSpecArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceSpec)(nil)).Elem()
}

func (i SpecialResourceSpecArgs) ToSpecialResourceSpecOutput() SpecialResourceSpecOutput {
	return i.ToSpecialResourceSpecOutputWithContext(context.Background())
}

func (i SpecialResourceSpecArgs) ToSpecialResourceSpecOutputWithContext(ctx context.Context) SpecialResourceSpecOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SpecialResourceSpecOutput)
}

// SpecialResourceSpec defines the desired state of SpecialResource
type SpecialResourceSpecOutput struct{ *pulumi.OutputState }

func (SpecialResourceSpecOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceSpec)(nil)).Elem()
}

func (o SpecialResourceSpecOutput) ToSpecialResourceSpecOutput() SpecialResourceSpecOutput {
	return o
}

func (o SpecialResourceSpecOutput) ToSpecialResourceSpecOutputWithContext(ctx context.Context) SpecialResourceSpecOutput {
	return o
}

// SpecialResourceStatus defines the observed state of SpecialResource
type SpecialResourceStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
	State string `pulumi:"state"`
}

// SpecialResourceStatusInput is an input type that accepts SpecialResourceStatusArgs and SpecialResourceStatusOutput values.
// You can construct a concrete instance of `SpecialResourceStatusInput` via:
//
//          SpecialResourceStatusArgs{...}
type SpecialResourceStatusInput interface {
	pulumi.Input

	ToSpecialResourceStatusOutput() SpecialResourceStatusOutput
	ToSpecialResourceStatusOutputWithContext(context.Context) SpecialResourceStatusOutput
}

// SpecialResourceStatus defines the observed state of SpecialResource
type SpecialResourceStatusArgs struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
	State pulumi.StringInput `pulumi:"state"`
}

func (SpecialResourceStatusArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceStatus)(nil)).Elem()
}

func (i SpecialResourceStatusArgs) ToSpecialResourceStatusOutput() SpecialResourceStatusOutput {
	return i.ToSpecialResourceStatusOutputWithContext(context.Background())
}

func (i SpecialResourceStatusArgs) ToSpecialResourceStatusOutputWithContext(ctx context.Context) SpecialResourceStatusOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SpecialResourceStatusOutput)
}

func (i SpecialResourceStatusArgs) ToSpecialResourceStatusPtrOutput() SpecialResourceStatusPtrOutput {
	return i.ToSpecialResourceStatusPtrOutputWithContext(context.Background())
}

func (i SpecialResourceStatusArgs) ToSpecialResourceStatusPtrOutputWithContext(ctx context.Context) SpecialResourceStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SpecialResourceStatusOutput).ToSpecialResourceStatusPtrOutputWithContext(ctx)
}

// SpecialResourceStatusPtrInput is an input type that accepts SpecialResourceStatusArgs, SpecialResourceStatusPtr and SpecialResourceStatusPtrOutput values.
// You can construct a concrete instance of `SpecialResourceStatusPtrInput` via:
//
//          SpecialResourceStatusArgs{...}
//
//  or:
//
//          nil
type SpecialResourceStatusPtrInput interface {
	pulumi.Input

	ToSpecialResourceStatusPtrOutput() SpecialResourceStatusPtrOutput
	ToSpecialResourceStatusPtrOutputWithContext(context.Context) SpecialResourceStatusPtrOutput
}

type specialResourceStatusPtrType SpecialResourceStatusArgs

func SpecialResourceStatusPtr(v *SpecialResourceStatusArgs) SpecialResourceStatusPtrInput {
	return (*specialResourceStatusPtrType)(v)
}

func (*specialResourceStatusPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SpecialResourceStatus)(nil)).Elem()
}

func (i *specialResourceStatusPtrType) ToSpecialResourceStatusPtrOutput() SpecialResourceStatusPtrOutput {
	return i.ToSpecialResourceStatusPtrOutputWithContext(context.Background())
}

func (i *specialResourceStatusPtrType) ToSpecialResourceStatusPtrOutputWithContext(ctx context.Context) SpecialResourceStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SpecialResourceStatusPtrOutput)
}

// SpecialResourceStatus defines the observed state of SpecialResource
type SpecialResourceStatusOutput struct{ *pulumi.OutputState }

func (SpecialResourceStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SpecialResourceStatus)(nil)).Elem()
}

func (o SpecialResourceStatusOutput) ToSpecialResourceStatusOutput() SpecialResourceStatusOutput {
	return o
}

func (o SpecialResourceStatusOutput) ToSpecialResourceStatusOutputWithContext(ctx context.Context) SpecialResourceStatusOutput {
	return o
}

func (o SpecialResourceStatusOutput) ToSpecialResourceStatusPtrOutput() SpecialResourceStatusPtrOutput {
	return o.ToSpecialResourceStatusPtrOutputWithContext(context.Background())
}

func (o SpecialResourceStatusOutput) ToSpecialResourceStatusPtrOutputWithContext(ctx context.Context) SpecialResourceStatusPtrOutput {
	return o.ApplyT(func(v SpecialResourceStatus) *SpecialResourceStatus {
		return &v
	}).(SpecialResourceStatusPtrOutput)
}

// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
func (o SpecialResourceStatusOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v SpecialResourceStatus) string { return v.State }).(pulumi.StringOutput)
}

type SpecialResourceStatusPtrOutput struct{ *pulumi.OutputState }

func (SpecialResourceStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SpecialResourceStatus)(nil)).Elem()
}

func (o SpecialResourceStatusPtrOutput) ToSpecialResourceStatusPtrOutput() SpecialResourceStatusPtrOutput {
	return o
}

func (o SpecialResourceStatusPtrOutput) ToSpecialResourceStatusPtrOutputWithContext(ctx context.Context) SpecialResourceStatusPtrOutput {
	return o
}

func (o SpecialResourceStatusPtrOutput) Elem() SpecialResourceStatusOutput {
	return o.ApplyT(func(v *SpecialResourceStatus) SpecialResourceStatus { return *v }).(SpecialResourceStatusOutput)
}

// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
func (o SpecialResourceStatusPtrOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SpecialResourceStatus) *string {
		if v == nil {
			return nil
		}
		return &v.State
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(SpecialResourceTypeOutput{})
	pulumi.RegisterOutputType(SpecialResourceMetadataOutput{})
	pulumi.RegisterOutputType(SpecialResourceSpecOutput{})
	pulumi.RegisterOutputType(SpecialResourceStatusOutput{})
	pulumi.RegisterOutputType(SpecialResourceStatusPtrOutput{})
}
