// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Multiclusterdns.V1Alpha1
{

    public class ServiceDNSRecordStatusDnsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster name
        /// </summary>
        [Input("cluster")]
        public Input<string>? Cluster { get; set; }

        [Input("loadBalancer")]
        private InputMap<object>? _loadBalancer;

        /// <summary>
        /// LoadBalancer for the corresponding service
        /// </summary>
        public InputMap<object> LoadBalancer
        {
            get => _loadBalancer ?? (_loadBalancer = new InputMap<object>());
            set => _loadBalancer = value;
        }

        /// <summary>
        /// Region to which the cluster belongs
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("zones")]
        private InputList<string>? _zones;

        /// <summary>
        /// Zones to which the cluster belongs
        /// </summary>
        public InputList<string> Zones
        {
            get => _zones ?? (_zones = new InputList<string>());
            set => _zones = value;
        }

        public ServiceDNSRecordStatusDnsArgs()
        {
        }
    }
}
