// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Retry controls failed sync retry behavior
    /// </summary>
    public class ApplicationSpecSyncPolicyRetryArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Backoff is a backoff strategy
        /// </summary>
        [Input("backoff")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSpecSyncPolicyRetryBackoffArgs>? Backoff { get; set; }

        /// <summary>
        /// Limit is the maximum number of attempts when retrying a container
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        public ApplicationSpecSyncPolicyRetryArgs()
        {
        }
    }
}
