// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// ApplicationDestination contains deployment destination information
    /// </summary>
    public class AppProjectSpecDestinationsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Namespace overrides the environment namespace value in the ksonnet app.yaml
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Server overrides the environment server value in the ksonnet app.yaml
        /// </summary>
        [Input("server")]
        public Input<string>? Server { get; set; }

        public AppProjectSpecDestinationsArgs()
        {
        }
    }
}
