// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1
{

    [OutputType]
    public sealed class JaegerSpecIngress
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressAffinity Affinity;
        public readonly ImmutableDictionary<string, string> Annotations;
        public readonly bool Enabled;
        public readonly ImmutableArray<string> Hosts;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressOpenshift Openshift;
        public readonly ImmutableDictionary<string, object> Options;
        public readonly Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressResources Resources;
        public readonly string SecretName;
        public readonly string Security;
        public readonly Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressSecurityContext SecurityContext;
        public readonly string ServiceAccount;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressTls> Tls;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressTolerations> Tolerations;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressVolumeMounts> VolumeMounts;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressVolumes> Volumes;

        [OutputConstructor]
        private JaegerSpecIngress(
            Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressAffinity affinity,

            ImmutableDictionary<string, string> annotations,

            bool enabled,

            ImmutableArray<string> hosts,

            ImmutableDictionary<string, string> labels,

            Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressOpenshift openshift,

            ImmutableDictionary<string, object> options,

            Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressResources resources,

            string secretName,

            string security,

            Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressSecurityContext securityContext,

            string serviceAccount,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressTls> tls,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressTolerations> tolerations,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressVolumeMounts> volumeMounts,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Jaegertracing.V1.JaegerSpecIngressVolumes> volumes)
        {
            Affinity = affinity;
            Annotations = annotations;
            Enabled = enabled;
            Hosts = hosts;
            Labels = labels;
            Openshift = openshift;
            Options = options;
            Resources = resources;
            SecretName = secretName;
            Security = security;
            SecurityContext = securityContext;
            ServiceAccount = serviceAccount;
            Tls = tls;
            Tolerations = tolerations;
            VolumeMounts = volumeMounts;
            Volumes = volumes;
        }
    }
}
