// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Datadoghq.V1Alpha1
{

    [OutputType]
    public sealed class DatadogAgentSpecClusterChecksRunnerCustomConfig
    {
        /// <summary>
        /// ConfigData corresponds to the configuration file content
        /// </summary>
        public readonly string ConfigData;
        /// <summary>
        /// ConfigMap name of a ConfigMap used to mount the configuration file
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Datadoghq.V1Alpha1.DatadogAgentSpecClusterChecksRunnerCustomConfigConfigMap ConfigMap;

        [OutputConstructor]
        private DatadogAgentSpecClusterChecksRunnerCustomConfig(
            string configData,

            Pulumi.Kubernetes.Types.Outputs.Datadoghq.V1Alpha1.DatadogAgentSpecClusterChecksRunnerCustomConfigConfigMap configMap)
        {
            ConfigData = configData;
            ConfigMap = configMap;
        }
    }
}
