// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Datadoghq.V1Alpha1
{

    [OutputType]
    public sealed class DatadogAgentSpecAgentSecurityCompliance
    {
        /// <summary>
        /// Check interval
        /// </summary>
        public readonly string CheckInterval;
        /// <summary>
        /// Config dir containing compliance benchmarks
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Datadoghq.V1Alpha1.DatadogAgentSpecAgentSecurityComplianceConfigDir ConfigDir;
        /// <summary>
        /// Enables continuous compliance monitoring
        /// </summary>
        public readonly bool Enabled;

        [OutputConstructor]
        private DatadogAgentSpecAgentSecurityCompliance(
            string checkInterval,

            Pulumi.Kubernetes.Types.Outputs.Datadoghq.V1Alpha1.DatadogAgentSpecAgentSecurityComplianceConfigDir configDir,

            bool enabled)
        {
            CheckInterval = checkInterval;
            ConfigDir = configDir;
            Enabled = enabled;
        }
    }
}
