// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1Alpha2
{

    /// <summary>
    /// Exec probes a container's health by executing a command.
    /// </summary>
    public class ContainerizedWorkloadSpecContainersLivenessProbeExecArgs : Pulumi.ResourceArgs
    {
        [Input("command", required: true)]
        private InputList<string>? _command;

        /// <summary>
        /// Command to be run by this probe.
        /// </summary>
        public InputList<string> Command
        {
            get => _command ?? (_command = new InputList<string>());
            set => _command = value;
        }

        public ContainerizedWorkloadSpecContainersLivenessProbeExecArgs()
        {
        }
    }
}
