// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1Alpha2
{

    /// <summary>
    /// A WorkloadDefinitionSpec defines the desired state of a WorkloadDefinition.
    /// </summary>
    public class WorkloadDefinitionSpecArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Reference to the CustomResourceDefinition that defines this workload kind.
        /// </summary>
        [Input("definitionRef", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Core.V1Alpha2.WorkloadDefinitionSpecDefinitionRefArgs> DefinitionRef { get; set; } = null!;

        public WorkloadDefinitionSpecArgs()
        {
        }
    }
}
