// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * ServiceDiscovery is the Schema for the servicediscoveries API
 */
export class ServiceDiscovery extends pulumi.CustomResource {
    /**
     * Get an existing ServiceDiscovery resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ServiceDiscovery {
        return new ServiceDiscovery(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:submariner.io/v1alpha1:ServiceDiscovery';

    /**
     * Returns true if the given object is an instance of ServiceDiscovery.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceDiscovery {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceDiscovery.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"submariner.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"ServiceDiscovery" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * ServiceDiscoverySpec defines the desired state of ServiceDiscovery
     */
    public readonly spec!: pulumi.Output<outputs.submariner.v1alpha1.ServiceDiscoverySpec | undefined>;
    /**
     * ServiceDiscoveryStatus defines the observed state of ServiceDiscovery
     */
    public readonly status!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a ServiceDiscovery resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServiceDiscoveryArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (!(opts && opts.id)) {
            inputs["apiVersion"] = "submariner.io/v1alpha1";
            inputs["kind"] = "ServiceDiscovery";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["spec"] = args ? args.spec : undefined;
            inputs["status"] = args ? args.status : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["spec"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(ServiceDiscovery.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a ServiceDiscovery resource.
 */
export interface ServiceDiscoveryArgs {
    readonly apiVersion?: pulumi.Input<"submariner.io/v1alpha1">;
    readonly kind?: pulumi.Input<"ServiceDiscovery">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    /**
     * ServiceDiscoverySpec defines the desired state of ServiceDiscovery
     */
    readonly spec?: pulumi.Input<inputs.submariner.v1alpha1.ServiceDiscoverySpec>;
    /**
     * ServiceDiscoveryStatus defines the observed state of ServiceDiscovery
     */
    readonly status?: pulumi.Input<{[key: string]: any}>;
}
