// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Apps.V1
{

    [OutputType]
    public sealed class HelmReleaseRepoSource
    {
        /// <summary>
        /// GitHub provides the parameters to access the helm-chart located in a github repo
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Apps.V1.HelmReleaseRepoSourceGithub Github;
        /// <summary>
        /// HelmRepo provides the urls to retrieve the helm-chart
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Apps.V1.HelmReleaseRepoSourceHelmRepo HelmRepo;
        /// <summary>
        /// SourceTypeEnum types of sources
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private HelmReleaseRepoSource(
            Pulumi.Kubernetes.Types.Outputs.Apps.V1.HelmReleaseRepoSourceGithub github,

            Pulumi.Kubernetes.Types.Outputs.Apps.V1.HelmReleaseRepoSourceHelmRepo helmRepo,

            string type)
        {
            Github = github;
            HelmRepo = helmRepo;
            Type = type;
        }
    }
}
