// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Hiveinternal.V1Alpha1
{

    /// <summary>
    /// SyncStatus is the status of applying a specific SyncSet or SelectorSyncSet to the cluster.
    /// </summary>
    public class ClusterSyncStatusSelectorSyncSetsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// FailureMessage is a message describing why the SyncSet or SelectorSyncSet could not be applied. This is only set when Result is Failure.
        /// </summary>
        [Input("failureMessage")]
        public Input<string>? FailureMessage { get; set; }

        /// <summary>
        /// FirstSuccessTime is the time when the SyncSet or SelectorSyncSet was first successfully applied to the cluster.
        /// </summary>
        [Input("firstSuccessTime")]
        public Input<string>? FirstSuccessTime { get; set; }

        /// <summary>
        /// LastTransitionTime is the time when this status last changed.
        /// </summary>
        [Input("lastTransitionTime", required: true)]
        public Input<string> LastTransitionTime { get; set; } = null!;

        /// <summary>
        /// Name is the name of the SyncSet or SelectorSyncSet.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// ObservedGeneration is the generation of the SyncSet or SelectorSyncSet that was last observed.
        /// </summary>
        [Input("observedGeneration", required: true)]
        public Input<int> ObservedGeneration { get; set; } = null!;

        [Input("resourcesToDelete")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Hiveinternal.V1Alpha1.ClusterSyncStatusSelectorSyncSetsResourcesToDeleteArgs>? _resourcesToDelete;

        /// <summary>
        /// ResourcesToDelete is the list of resources in the cluster that should be deleted when the SyncSet or SelectorSyncSet is deleted or is no longer matched to the cluster.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Hiveinternal.V1Alpha1.ClusterSyncStatusSelectorSyncSetsResourcesToDeleteArgs> ResourcesToDelete
        {
            get => _resourcesToDelete ?? (_resourcesToDelete = new InputList<Pulumi.Kubernetes.Types.Inputs.Hiveinternal.V1Alpha1.ClusterSyncStatusSelectorSyncSetsResourcesToDeleteArgs>());
            set => _resourcesToDelete = value;
        }

        /// <summary>
        /// Result is the result of the last attempt to apply the SyncSet or SelectorSyncSet to the cluster.
        /// </summary>
        [Input("result", required: true)]
        public Input<string> Result { get; set; } = null!;

        public ClusterSyncStatusSelectorSyncSetsArgs()
        {
        }
    }
}
