// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Redhatcop.V1Alpha1
{

    /// <summary>
    /// LockedResourceTemplate represents a resource template in go language to be enforced in a LockedResourceController and can be used in a API specification
    /// </summary>
    public class NamespaceConfigSpecTemplatesArgs : Pulumi.ResourceArgs
    {
        [Input("excludedPaths")]
        private InputList<string>? _excludedPaths;

        /// <summary>
        /// ExludedPaths are a set of json paths that need not be considered by the LockedResourceReconciler
        /// </summary>
        public InputList<string> ExcludedPaths
        {
            get => _excludedPaths ?? (_excludedPaths = new InputList<string>());
            set => _excludedPaths = value;
        }

        /// <summary>
        /// ObjectTemplate is a goland template. Whne processed, it must resolve to a yaml representation of an API resource
        /// </summary>
        [Input("objectTemplate", required: true)]
        public Input<string> ObjectTemplate { get; set; } = null!;

        public NamespaceConfigSpecTemplatesArgs()
        {
        }
    }
}
