// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * AddressPlan describes the resource usage and common properties of an address. This resource is created by the service administrator.
 */
export class AddressPlan extends pulumi.CustomResource {
    /**
     * Get an existing AddressPlan resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AddressPlan {
        return new AddressPlan(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:admin.enmasse.io/v1beta2:AddressPlan';

    /**
     * Returns true if the given object is an instance of AddressPlan.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AddressPlan {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AddressPlan.__pulumiType;
    }

    public readonly addressType!: pulumi.Output<string | undefined>;
    public readonly apiVersion!: pulumi.Output<"admin.enmasse.io/v1beta2" | undefined>;
    public readonly displayName!: pulumi.Output<string | undefined>;
    public readonly displayOrder!: pulumi.Output<number | undefined>;
    public readonly kind!: pulumi.Output<"AddressPlan" | undefined>;
    public readonly longDescription!: pulumi.Output<string | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    public readonly requiredResources!: pulumi.Output<outputs.admin.v1beta2.AddressPlanRequiredResources[] | undefined>;
    public readonly shortDescription!: pulumi.Output<string | undefined>;
    public readonly spec!: pulumi.Output<outputs.admin.v1beta2.AddressPlanSpec | undefined>;
    public readonly status!: pulumi.Output<any | undefined>;
    public readonly uuid!: pulumi.Output<string | undefined>;

    /**
     * Create a AddressPlan resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AddressPlanArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (!(opts && opts.id)) {
            inputs["addressType"] = args ? args.addressType : undefined;
            inputs["apiVersion"] = "admin.enmasse.io/v1beta2";
            inputs["displayName"] = args ? args.displayName : undefined;
            inputs["displayOrder"] = args ? args.displayOrder : undefined;
            inputs["kind"] = "AddressPlan";
            inputs["longDescription"] = args ? args.longDescription : undefined;
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["requiredResources"] = args ? args.requiredResources : undefined;
            inputs["shortDescription"] = args ? args.shortDescription : undefined;
            inputs["spec"] = args ? args.spec : undefined;
            inputs["status"] = args ? args.status : undefined;
            inputs["uuid"] = args ? args.uuid : undefined;
        } else {
            inputs["addressType"] = undefined /*out*/;
            inputs["apiVersion"] = undefined /*out*/;
            inputs["displayName"] = undefined /*out*/;
            inputs["displayOrder"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["longDescription"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["requiredResources"] = undefined /*out*/;
            inputs["shortDescription"] = undefined /*out*/;
            inputs["spec"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
            inputs["uuid"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(AddressPlan.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a AddressPlan resource.
 */
export interface AddressPlanArgs {
    readonly addressType?: pulumi.Input<string>;
    readonly apiVersion?: pulumi.Input<"admin.enmasse.io/v1beta2">;
    readonly displayName?: pulumi.Input<string>;
    readonly displayOrder?: pulumi.Input<number>;
    readonly kind?: pulumi.Input<"AddressPlan">;
    readonly longDescription?: pulumi.Input<string>;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    readonly requiredResources?: pulumi.Input<pulumi.Input<inputs.admin.v1beta2.AddressPlanRequiredResources>[]>;
    readonly shortDescription?: pulumi.Input<string>;
    readonly spec?: pulumi.Input<inputs.admin.v1beta2.AddressPlanSpec>;
    readonly status?: any;
    readonly uuid?: pulumi.Input<string>;
}
