// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Multiclusterdns.V1Alpha1
{

    [OutputType]
    public sealed class IngressDNSRecordSpec
    {
        /// <summary>
        /// Host from the IngressRule in Cluster Ingress Spec
        /// </summary>
        public readonly ImmutableArray<string> Hosts;
        /// <summary>
        /// RecordTTL is the TTL in seconds for DNS records created for the Ingress, if omitted a default would be used
        /// </summary>
        public readonly int RecordTTL;

        [OutputConstructor]
        private IngressDNSRecordSpec(
            ImmutableArray<string> hosts,

            int recordTTL)
        {
            Hosts = hosts;
            RecordTTL = recordTTL;
        }
    }
}
