// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Deploy.V1Alpha1
{

    /// <summary>
    /// Details about the container's last termination condition.
    /// </summary>
    public class OperatorStatusInitContainerStatusesLastStateArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Details about a running container
        /// </summary>
        [Input("running")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Deploy.V1Alpha1.OperatorStatusInitContainerStatusesLastStateRunningArgs>? Running { get; set; }

        /// <summary>
        /// Details about a terminated container
        /// </summary>
        [Input("terminated")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Deploy.V1Alpha1.OperatorStatusInitContainerStatusesLastStateTerminatedArgs>? Terminated { get; set; }

        /// <summary>
        /// Details about a waiting container
        /// </summary>
        [Input("waiting")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Deploy.V1Alpha1.OperatorStatusInitContainerStatusesLastStateWaitingArgs>? Waiting { get; set; }

        public OperatorStatusInitContainerStatusesLastStateArgs()
        {
        }
    }
}
