// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Apps.V1Alpha1
{

    /// <summary>
    /// ServerOperationsStatus describes the general status for the operations performed in the Nexus server instance
    /// </summary>
    public class NexusStatusServerOperationsStatusArgs : Pulumi.ResourceArgs
    {
        [Input("communityRepositoriesCreated")]
        public Input<bool>? CommunityRepositoriesCreated { get; set; }

        [Input("mavenCentralUpdated")]
        public Input<bool>? MavenCentralUpdated { get; set; }

        [Input("mavenPublicURL")]
        public Input<string>? MavenPublicURL { get; set; }

        [Input("operatorUserCreated")]
        public Input<bool>? OperatorUserCreated { get; set; }

        [Input("reason")]
        public Input<string>? Reason { get; set; }

        [Input("serverReady")]
        public Input<bool>? ServerReady { get; set; }

        public NexusStatusServerOperationsStatusArgs()
        {
        }
    }
}
