// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Kubernetes.Crds.Operators.Crossplane.Apiextensions.V1Alpha1
{
    /// <summary>
    /// Composition defines the group of resources to be created when a compatible type is created with reference to the composition.
    /// </summary>
    public partial class Composition : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// CompositionSpec specifies the desired state of the definition.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Apiextensions.V1Alpha1.CompositionSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// CompositionStatus shows the observed state of the composition.
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Apiextensions.V1Alpha1.CompositionStatus> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Composition resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Composition(string name, Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1.CompositionArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:apiextensions.crossplane.io/v1alpha1:Composition", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal Composition(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:apiextensions.crossplane.io/v1alpha1:Composition", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private Composition(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:apiextensions.crossplane.io/v1alpha1:Composition", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1.CompositionArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1.CompositionArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1.CompositionArgs();
            args.ApiVersion = "apiextensions.crossplane.io/v1alpha1";
            args.Kind = "Composition";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Composition resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Composition Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Composition(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1
{

    public class CompositionArgs : Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// CompositionSpec specifies the desired state of the definition.
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1.CompositionSpecArgs>? Spec { get; set; }

        /// <summary>
        /// CompositionStatus shows the observed state of the composition.
        /// </summary>
        [Input("status")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Apiextensions.V1Alpha1.CompositionStatusArgs>? Status { get; set; }

        public CompositionArgs()
        {
        }
    }
}
