// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1Alpha1
{

    /// <summary>
    /// The desired behavior of the storage node. Currently changing the spec does not affect the actual storage node in the cluster. Eventually spec in StorageNode will override the spec from StorageCluster so that configuration can be overridden at node level.
    /// </summary>
    public class StorageNodeSpecArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Details of storage on the node for cloud environments.
        /// </summary>
        [Input("cloudStorage")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Core.V1Alpha1.StorageNodeSpecCloudStorageArgs>? CloudStorage { get; set; }

        /// <summary>
        /// Version of the storage driver on the node.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public StorageNodeSpecArgs()
        {
        }
    }
}
