// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Keycloak.V1Alpha1
{

    /// <summary>
    /// If provided, an automatic database backup will be created on AWS S3 instead of a local Persistent Volume. If this property is not provided - a local Persistent Volume backup will be chosen.
    /// </summary>
    public class KeycloakBackupSpecAwsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Provides a secret name used for connecting to AWS S3 Service. The secret needs to be in the following form: 
        ///      apiVersion: v1     kind: Secret     metadata:       name: &lt;Secret name&gt;     type: Opaque     stringData:       AWS_S3_BUCKET_NAME: &lt;S3 Bucket Name&gt;       AWS_ACCESS_KEY_ID: &lt;AWS Access Key ID&gt;       AWS_SECRET_ACCESS_KEY: &lt;AWS Secret Key&gt; 
        ///  For more information, please refer to the Operator documentation.
        /// </summary>
        [Input("credentialsSecretName")]
        public Input<string>? CredentialsSecretName { get; set; }

        /// <summary>
        /// If provided, the database backup will be encrypted. Provides a secret name used for encrypting database data. The secret needs to be in the following form: 
        ///      apiVersion: v1     kind: Secret     metadata:       name: &lt;Secret name&gt;     type: Opaque     stringData:       GPG_PUBLIC_KEY: &lt;GPG Public Key&gt;       GPG_TRUST_MODEL: &lt;GPG Trust Model&gt;       GPG_RECIPIENT: &lt;GPG Recipient&gt; 
        ///  For more information, please refer to the Operator documentation.
        /// </summary>
        [Input("encryptionKeySecretName")]
        public Input<string>? EncryptionKeySecretName { get; set; }

        /// <summary>
        /// If specified, it will be used as a schedule for creating a CronJob.
        /// </summary>
        [Input("schedule")]
        public Input<string>? Schedule { get; set; }

        public KeycloakBackupSpecAwsArgs()
        {
        }
    }
}
