// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Keda.V1Alpha1
{

    /// <summary>
    /// ScaledObjectStatus is the status for a ScaledObject resource
    /// </summary>
    public class ScaledObjectStatusArgs : Pulumi.ResourceArgs
    {
        [Input("externalMetricNames")]
        private InputList<string>? _externalMetricNames;
        public InputList<string> ExternalMetricNames
        {
            get => _externalMetricNames ?? (_externalMetricNames = new InputList<string>());
            set => _externalMetricNames = value;
        }

        [Input("lastActiveTime")]
        public Input<string>? LastActiveTime { get; set; }

        public ScaledObjectStatusArgs()
        {
        }
    }
}
