// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Maistra.V2
{

    [OutputType]
    public sealed class ServiceMeshControlPlaneSpecAddons3scaleGrpc
    {
        public readonly int Max_conn_timeout;

        [OutputConstructor]
        private ServiceMeshControlPlaneSpecAddons3scaleGrpc(int max_conn_timeout)
        {
            Max_conn_timeout = max_conn_timeout;
        }
    }
}
