// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Maistra.V2
{

    [OutputType]
    public sealed class ServiceMeshControlPlaneSpecGatewaysEgress
    {
        public readonly bool Enabled;
        public readonly string Namespace;
        public readonly ImmutableArray<string> RequestedNetworkView;
        public readonly string RouterMode;
        public readonly Pulumi.Kubernetes.Types.Outputs.Maistra.V2.ServiceMeshControlPlaneSpecGatewaysEgressRuntime Runtime;
        public readonly Pulumi.Kubernetes.Types.Outputs.Maistra.V2.ServiceMeshControlPlaneSpecGatewaysEgressService Service;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Maistra.V2.ServiceMeshControlPlaneSpecGatewaysEgressVolumes> Volumes;

        [OutputConstructor]
        private ServiceMeshControlPlaneSpecGatewaysEgress(
            bool enabled,

            string @namespace,

            ImmutableArray<string> requestedNetworkView,

            string routerMode,

            Pulumi.Kubernetes.Types.Outputs.Maistra.V2.ServiceMeshControlPlaneSpecGatewaysEgressRuntime runtime,

            Pulumi.Kubernetes.Types.Outputs.Maistra.V2.ServiceMeshControlPlaneSpecGatewaysEgressService service,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Maistra.V2.ServiceMeshControlPlaneSpecGatewaysEgressVolumes> volumes)
        {
            Enabled = enabled;
            Namespace = @namespace;
            RequestedNetworkView = requestedNetworkView;
            RouterMode = routerMode;
            Runtime = runtime;
            Service = service;
            Volumes = volumes;
        }
    }
}
