// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Maistra.V2
{

    [OutputType]
    public sealed class ServiceMeshControlPlaneStatusAppliedSpecSecurityControlPlaneTls
    {
        public readonly ImmutableArray<string> CipherSuites;
        public readonly ImmutableArray<string> EcdhCurves;
        public readonly string MaxProtocolVersion;
        public readonly string MinProtocolVersion;

        [OutputConstructor]
        private ServiceMeshControlPlaneStatusAppliedSpecSecurityControlPlaneTls(
            ImmutableArray<string> cipherSuites,

            ImmutableArray<string> ecdhCurves,

            string maxProtocolVersion,

            string minProtocolVersion)
        {
            CipherSuites = cipherSuites;
            EcdhCurves = ecdhCurves;
            MaxProtocolVersion = maxProtocolVersion;
            MinProtocolVersion = minProtocolVersion;
        }
    }
}
