// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Maistra.V2
{

    [OutputType]
    public sealed class ServiceMeshControlPlaneSpecAddonsStackdriverTelemetryAuth
    {
        public readonly string ApiKey;
        public readonly bool AppCredentials;
        public readonly string ServiceAccountPath;

        [OutputConstructor]
        private ServiceMeshControlPlaneSpecAddonsStackdriverTelemetryAuth(
            string apiKey,

            bool appCredentials,

            string serviceAccountPath)
        {
            ApiKey = apiKey;
            AppCredentials = appCredentials;
            ServiceAccountPath = serviceAccountPath;
        }
    }
}
