# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

SNAKE_TO_CAMEL_CASE_TABLE = {
    "api_version": "apiVersion",
    "container_id": "containerID",
    "container_statuses": "containerStatuses",
    "ephemeral_container_statuses": "ephemeralContainerStatuses",
    "exit_code": "exitCode",
    "finished_at": "finishedAt",
    "host_ip": "hostIP",
    "image_id": "imageID",
    "init_container_statuses": "initContainerStatuses",
    "last_probe_time": "lastProbeTime",
    "last_state": "lastState",
    "last_transition_time": "lastTransitionTime",
    "nominated_node_name": "nominatedNodeName",
    "pod_i_ps": "podIPs",
    "pod_ip": "podIP",
    "qos_class": "qosClass",
    "restart_count": "restartCount",
    "secret_ref": "secretRef",
    "start_time": "startTime",
    "started_at": "startedAt",
}

CAMEL_TO_SNAKE_CASE_TABLE = {
    "apiVersion": "api_version",
    "containerID": "container_id",
    "containerStatuses": "container_statuses",
    "ephemeralContainerStatuses": "ephemeral_container_statuses",
    "exitCode": "exit_code",
    "finishedAt": "finished_at",
    "hostIP": "host_ip",
    "imageID": "image_id",
    "initContainerStatuses": "init_container_statuses",
    "lastProbeTime": "last_probe_time",
    "lastState": "last_state",
    "lastTransitionTime": "last_transition_time",
    "nominatedNodeName": "nominated_node_name",
    "podIPs": "pod_i_ps",
    "podIP": "pod_ip",
    "qosClass": "qos_class",
    "restartCount": "restart_count",
    "secretRef": "secret_ref",
    "startTime": "start_time",
    "startedAt": "started_at",
}
