// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.App.V1Beta1
{

    [OutputType]
    public sealed class KogitoInfraStatusVolumesVolume
    {
        /// <summary>
        /// ConfigMap represents a configMap that should populate this volume
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.App.V1Beta1.KogitoInfraStatusVolumesVolumeConfigMap ConfigMap;
        /// <summary>
        /// Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Secret represents a secret that should populate this volume. More info: https://kubernetes.io/docs/concepts/storage/volumes#secret
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.App.V1Beta1.KogitoInfraStatusVolumesVolumeSecret Secret;

        [OutputConstructor]
        private KogitoInfraStatusVolumesVolume(
            Pulumi.Kubernetes.Types.Outputs.App.V1Beta1.KogitoInfraStatusVolumesVolumeConfigMap configMap,

            string name,

            Pulumi.Kubernetes.Types.Outputs.App.V1Beta1.KogitoInfraStatusVolumesVolumeSecret secret)
        {
            ConfigMap = configMap;
            Name = name;
            Secret = secret;
        }
    }
}
