// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Admin.V1Beta1
{

    public class ConsoleServiceSpecOauthProxyArgs : Pulumi.ResourceArgs
    {
        [Input("extraArgs")]
        private InputList<string>? _extraArgs;

        /// <summary>
        /// Extra arguments to pass to oauth-proxy
        /// </summary>
        public InputList<string> ExtraArgs
        {
            get => _extraArgs ?? (_extraArgs = new InputList<string>());
            set => _extraArgs = value;
        }

        [Input("resources")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Admin.V1Beta1.ConsoleServiceSpecOauthProxyResourcesArgs>? Resources { get; set; }

        public ConsoleServiceSpecOauthProxyArgs()
        {
        }
    }
}
