// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Iot.V1Alpha1
{

    public class IoTProjectStatusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The input accepted from the `.spec.configuration` section, split up into the different areas.
        /// </summary>
        [Input("accepted")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Iot.V1Alpha1.IoTProjectStatusAcceptedArgs>? Accepted { get; set; }

        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Iot.V1Alpha1.IoTProjectStatusConditionsArgs>? _conditions;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Iot.V1Alpha1.IoTProjectStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Iot.V1Alpha1.IoTProjectStatusConditionsArgs>());
            set => _conditions = value;
        }

        [Input("message")]
        public Input<string>? Message { get; set; }

        [Input("phase")]
        public Input<string>? Phase { get; set; }

        [Input("tenantName")]
        public Input<string>? TenantName { get; set; }

        public IoTProjectStatusArgs()
        {
        }
    }
}
