// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * HelmRelease is the Schema for the subscriptionreleases API
 */
export class HelmRelease extends pulumi.CustomResource {
    /**
     * Get an existing HelmRelease resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): HelmRelease {
        return new HelmRelease(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:apps.open-cluster-management.io/v1:HelmRelease';

    /**
     * Returns true if the given object is an instance of HelmRelease.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is HelmRelease {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === HelmRelease.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"apps.open-cluster-management.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"HelmRelease" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * HelmReleaseRepo defines the repository of HelmRelease
     */
    public readonly repo!: pulumi.Output<outputs.apps.v1.HelmReleaseRepo | undefined>;
    public readonly spec!: pulumi.Output<any | undefined>;
    public readonly status!: pulumi.Output<outputs.apps.v1.HelmReleaseStatus | undefined>;

    /**
     * Create a HelmRelease resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: HelmReleaseArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (!(opts && opts.id)) {
            inputs["apiVersion"] = "apps.open-cluster-management.io/v1";
            inputs["kind"] = "HelmRelease";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["repo"] = args ? args.repo : undefined;
            inputs["spec"] = args ? args.spec : undefined;
            inputs["status"] = args ? args.status : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["repo"] = undefined /*out*/;
            inputs["spec"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(HelmRelease.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a HelmRelease resource.
 */
export interface HelmReleaseArgs {
    readonly apiVersion?: pulumi.Input<"apps.open-cluster-management.io/v1">;
    readonly kind?: pulumi.Input<"HelmRelease">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    /**
     * HelmReleaseRepo defines the repository of HelmRelease
     */
    readonly repo?: pulumi.Input<inputs.apps.v1.HelmReleaseRepo>;
    readonly spec?: any;
    readonly status?: pulumi.Input<inputs.apps.v1.HelmReleaseStatus>;
}
