// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Packages.V1Alpha1
{

    [OutputType]
    public sealed class PackageSpecIcons
    {
        public readonly string Base64Data;
        public readonly string Mediatype;

        [OutputConstructor]
        private PackageSpecIcons(
            string base64Data,

            string mediatype)
        {
            Base64Data = base64Data;
            Mediatype = mediatype;
        }
    }
}
