// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Enmasse.V1Beta1
{

    [OutputType]
    public sealed class AddressSpecMessageTtl
    {
        /// <summary>
        /// Imposes a maximum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values greater than this value (or no TTL value) will have their expiration adjusted.
        /// </summary>
        public readonly int Maximum;
        /// <summary>
        /// Imposes a minimum TTL value (in milliseconds) for messages arriving at the address.  Messages arriving with TTL values less than this value will have their expiration adjusted.
        /// </summary>
        public readonly int Minimum;

        [OutputConstructor]
        private AddressSpecMessageTtl(
            int maximum,

            int minimum)
        {
            Maximum = maximum;
            Minimum = minimum;
        }
    }
}
