// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Enmasse.V1Beta1
{

    [OutputType]
    public sealed class AddressSpaceSpecEndpointsExports
    {
        /// <summary>
        /// Type of resource to export address space information into.
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Name of resource to export address space information into.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private AddressSpaceSpecEndpointsExports(
            string kind,

            string name)
        {
            Kind = kind;
            Name = name;
        }
    }
}
