// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Enmasse.V1Beta1
{

    [OutputType]
    public sealed class AddressSpecForwarders
    {
        public readonly string Direction;
        /// <summary>
        /// Forwarder name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Remote address to forward to. Must be prefixed with connector name.
        /// </summary>
        public readonly string RemoteAddress;

        [OutputConstructor]
        private AddressSpecForwarders(
            string direction,

            string name,

            string remoteAddress)
        {
            Direction = direction;
            Name = name;
            RemoteAddress = remoteAddress;
        }
    }
}
