// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Velero.V1
{

    [OutputType]
    public sealed class PodVolumeBackupStatusProgress
    {
        public readonly int BytesDone;
        public readonly int TotalBytes;

        [OutputConstructor]
        private PodVolumeBackupStatusProgress(
            int bytesDone,

            int totalBytes)
        {
            BytesDone = bytesDone;
            TotalBytes = totalBytes;
        }
    }
}
