// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Velero.V1
{

    [OutputType]
    public sealed class ScheduleSpecTemplateHooksResources
    {
        /// <summary>
        /// ExcludedNamespaces specifies the namespaces to which this hook spec does not apply.
        /// </summary>
        public readonly ImmutableArray<string> ExcludedNamespaces;
        /// <summary>
        /// ExcludedResources specifies the resources to which this hook spec does not apply.
        /// </summary>
        public readonly ImmutableArray<string> ExcludedResources;
        /// <summary>
        /// IncludedNamespaces specifies the namespaces to which this hook spec applies. If empty, it applies to all namespaces.
        /// </summary>
        public readonly ImmutableArray<string> IncludedNamespaces;
        /// <summary>
        /// IncludedResources specifies the resources to which this hook spec applies. If empty, it applies to all resources.
        /// </summary>
        public readonly ImmutableArray<string> IncludedResources;
        /// <summary>
        /// LabelSelector, if specified, filters the resources to which this hook spec applies.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Velero.V1.ScheduleSpecTemplateHooksResourcesLabelSelector LabelSelector;
        /// <summary>
        /// Name is the name of this hook.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// PostHooks is a list of BackupResourceHooks to execute after storing the item in the backup. These are executed after all "additional items" from item actions are processed.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Velero.V1.ScheduleSpecTemplateHooksResourcesPost> Post;
        /// <summary>
        /// PreHooks is a list of BackupResourceHooks to execute prior to storing the item in the backup. These are executed before any "additional items" from item actions are processed.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Velero.V1.ScheduleSpecTemplateHooksResourcesPre> Pre;

        [OutputConstructor]
        private ScheduleSpecTemplateHooksResources(
            ImmutableArray<string> excludedNamespaces,

            ImmutableArray<string> excludedResources,

            ImmutableArray<string> includedNamespaces,

            ImmutableArray<string> includedResources,

            Pulumi.Kubernetes.Types.Outputs.Velero.V1.ScheduleSpecTemplateHooksResourcesLabelSelector labelSelector,

            string name,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Velero.V1.ScheduleSpecTemplateHooksResourcesPost> post,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Velero.V1.ScheduleSpecTemplateHooksResourcesPre> pre)
        {
            ExcludedNamespaces = excludedNamespaces;
            ExcludedResources = excludedResources;
            IncludedNamespaces = includedNamespaces;
            IncludedResources = includedResources;
            LabelSelector = labelSelector;
            Name = name;
            Post = post;
            Pre = pre;
        }
    }
}
