// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Hyperfoil.V1Alpha2
{

    [OutputType]
    public sealed class HyperfoilSpecAuth
    {
        /// <summary>
        /// Optional; Name of secret used for basic authentication. Must contain key 'password'.
        /// </summary>
        public readonly string Secret;

        [OutputConstructor]
        private HyperfoilSpecAuth(string secret)
        {
            Secret = secret;
        }
    }
}
