// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1
{

    [OutputType]
    public sealed class TopicSpec
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecApiKey ApiKey;
        public readonly Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecBindingFrom BindingFrom;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecConfigs> Configs;
        public readonly Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecKafkaAdminUrl KafkaAdminUrl;
        public readonly int NumPartitions;
        public readonly int ReplicationFactor;
        public readonly string TopicName;

        [OutputConstructor]
        private TopicSpec(
            Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecApiKey apiKey,

            Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecBindingFrom bindingFrom,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecConfigs> configs,

            Pulumi.Kubernetes.Types.Outputs.Ibmcloud.V1Alpha1.TopicSpecKafkaAdminUrl kafkaAdminUrl,

            int numPartitions,

            int replicationFactor,

            string topicName)
        {
            ApiKey = apiKey;
            BindingFrom = bindingFrom;
            Configs = configs;
            KafkaAdminUrl = kafkaAdminUrl;
            NumPartitions = numPartitions;
            ReplicationFactor = replicationFactor;
            TopicName = topicName;
        }
    }
}
