// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1Alpha2
{

    /// <summary>
    /// Reference to a workload created by an ApplicationConfiguration.
    /// </summary>
    public class ApplicationConfigurationStatusWorkloadsWorkloadRefArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// APIVersion of the referenced object.
        /// </summary>
        [Input("apiVersion", required: true)]
        public Input<string> ApiVersion { get; set; } = null!;

        /// <summary>
        /// Kind of the referenced object.
        /// </summary>
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        /// <summary>
        /// Name of the referenced object.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// UID of the referenced object.
        /// </summary>
        [Input("uid")]
        public Input<string>? Uid { get; set; }

        public ApplicationConfigurationStatusWorkloadsWorkloadRefArgs()
        {
        }
    }
}
