// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Hive.V1
{

    /// <summary>
    /// ImageSetRef is a reference to a ClusterImageSet. If a value is specified for ReleaseImage, that will take precedence over the one from the ClusterImageSet.
    /// </summary>
    public class ClusterDeploymentSpecProvisioningImageSetRefArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name is the name of the ClusterImageSet that this refers to
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public ClusterDeploymentSpecProvisioningImageSetRefArgs()
        {
        }
    }
}
