// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Hive.V1
{

    /// <summary>
    /// ClusterDeploymentStatus defines the observed state of ClusterDeployment
    /// </summary>
    public class ClusterDeploymentStatusArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// APIURL is the URL where the cluster's API can be accessed.
        /// </summary>
        [Input("apiURL")]
        public Input<string>? ApiURL { get; set; }

        [Input("certificateBundles")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusCertificateBundlesArgs>? _certificateBundles;

        /// <summary>
        /// CertificateBundles contains of the status of the certificate bundles associated with this cluster deployment.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusCertificateBundlesArgs> CertificateBundles
        {
            get => _certificateBundles ?? (_certificateBundles = new InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusCertificateBundlesArgs>());
            set => _certificateBundles = value;
        }

        /// <summary>
        /// CLIImage is the name of the oc cli image to use when installing the target cluster
        /// </summary>
        [Input("cliImage")]
        public Input<string>? CliImage { get; set; }

        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusConditionsArgs>? _conditions;

        /// <summary>
        /// Conditions includes more detailed status for the cluster deployment
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// InstallRestarts is the total count of container restarts on the clusters install job.
        /// </summary>
        [Input("installRestarts")]
        public Input<int>? InstallRestarts { get; set; }

        /// <summary>
        /// InstalledTimestamp is the time we first detected that the cluster has been successfully installed.
        /// </summary>
        [Input("installedTimestamp")]
        public Input<string>? InstalledTimestamp { get; set; }

        /// <summary>
        /// InstallerImage is the name of the installer image to use when installing the target cluster
        /// </summary>
        [Input("installerImage")]
        public Input<string>? InstallerImage { get; set; }

        /// <summary>
        /// ProvisionRef is a reference to the last ClusterProvision created for the deployment
        /// </summary>
        [Input("provisionRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Hive.V1.ClusterDeploymentStatusProvisionRefArgs>? ProvisionRef { get; set; }

        /// <summary>
        /// WebConsoleURL is the URL for the cluster's web console UI.
        /// </summary>
        [Input("webConsoleURL")]
        public Input<string>? WebConsoleURL { get; set; }

        public ClusterDeploymentStatusArgs()
        {
        }
    }
}
