// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Hive.V1
{

    /// <summary>
    /// MachinePoolSpec defines the desired state of MachinePool
    /// </summary>
    public class MachinePoolSpecArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Autoscaling is the details for auto-scaling the machine pool. Replicas and autoscaling cannot be used together.
        /// </summary>
        [Input("autoscaling")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Hive.V1.MachinePoolSpecAutoscalingArgs>? Autoscaling { get; set; }

        /// <summary>
        /// ClusterDeploymentRef references the cluster deployment to which this machine pool belongs.
        /// </summary>
        [Input("clusterDeploymentRef", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Hive.V1.MachinePoolSpecClusterDeploymentRefArgs> ClusterDeploymentRef { get; set; } = null!;

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Map of label string keys and values that will be applied to the created MachineSet's MachineSpec. This list will overwrite any modifications made to Node labels on an ongoing basis.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Name is the name of the machine pool.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Platform is configuration for machine pool specific to the platform.
        /// </summary>
        [Input("platform", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Hive.V1.MachinePoolSpecPlatformArgs> Platform { get; set; } = null!;

        /// <summary>
        /// Replicas is the count of machines for this machine pool. Replicas and autoscaling cannot be used together. Default is 1, if autoscaling is not used.
        /// </summary>
        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        [Input("taints")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.MachinePoolSpecTaintsArgs>? _taints;

        /// <summary>
        /// List of taints that will be applied to the created MachineSet's MachineSpec. This list will overwrite any modifications made to Node taints on an ongoing basis.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.MachinePoolSpecTaintsArgs> Taints
        {
            get => _taints ?? (_taints = new InputList<Pulumi.Kubernetes.Types.Inputs.Hive.V1.MachinePoolSpecTaintsArgs>());
            set => _taints = value;
        }

        public MachinePoolSpecArgs()
        {
        }
    }
}
