// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Hive.V1
{

    /// <summary>
    /// tlsClientKey is an optional reference to a secret by name that contains the PEM-encoded TLS private key for the client certificate referenced in tlsClientCert. The key "tls.key" is used to locate the data. If specified and the secret or expected key is not found, the identity provider is not honored. If the specified certificate data is not valid, the identity provider is not honored. The namespace for this secret is openshift-config.
    /// </summary>
    public class SelectorSyncIdentityProviderSpecIdentityProvidersBasicAuthTlsClientKeyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// name is the metadata.name of the referenced secret
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public SelectorSyncIdentityProviderSpecIdentityProvidersBasicAuthTlsClientKeyArgs()
        {
        }
    }
}
