// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Hive.V1
{

    /// <summary>
    /// google enables user authentication using Google credentials
    /// </summary>
    public class SyncIdentityProviderSpecIdentityProvidersGoogleArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// clientID is the oauth client ID
        /// </summary>
        [Input("clientID")]
        public Input<string>? ClientID { get; set; }

        /// <summary>
        /// clientSecret is a required reference to the secret by name containing the oauth client secret. The key "clientSecret" is used to locate the data. If the secret or expected key is not found, the identity provider is not honored. The namespace for this secret is openshift-config.
        /// </summary>
        [Input("clientSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Hive.V1.SyncIdentityProviderSpecIdentityProvidersGoogleClientSecretArgs>? ClientSecret { get; set; }

        /// <summary>
        /// hostedDomain is the optional Google App domain (e.g. "mycompany.com") to restrict logins to
        /// </summary>
        [Input("hostedDomain")]
        public Input<string>? HostedDomain { get; set; }

        public SyncIdentityProviderSpecIdentityProvidersGoogleArgs()
        {
        }
    }
}
